IPATH+=${ROOT}/sources
IPATH+=${ROOT}/sources/app
IPATH+=${ROOT}/sources/os
IPATH+=${ROOT}/sources/dev
IPATH+=${ROOT}/sources/interface
IPATH+=${ROOT}/sources/utility
IPATH+=${ROOT}/sources/hal
IPATH+=${RTOS_SOURCE_DIR}/include
IPATH+=${RTOS_SOURCE_DIR}/portable/GCC/ARM_CM4F
IPATH+=${ROOT}/libraries/STM32F30x_StdPeriph_Driver/inc
IPATH+=${ROOT}/libraries/CMSIS/Include
IPATH+=${ROOT}/libraries

VPATH+=${ROOT}/sources
VPATH+=${ROOT}/sources/dev
VPATH+=${ROOT}/sources/os
VPATH+=${ROOT}/sources/app
VPATH+=${ROOT}/sources/interface
VPATH+=${ROOT}/sources/hal

####################################DebugInterface############################################

${BINDIR}/pmd_DebugInterface_ut.bin: DEFINES+=-DDEBUG
${BINDIR}/pmd_DebugInterface_ut.bin: ${OBJDIR}/pmd_DebugInterface_ut.o 
${BINDIR}/pmd_DebugInterface_ut.bin: ${OBJDIR}/pmd_DebugInterface.o
${BINDIR}/pmd_DebugInterface_ut.bin: ${OBJDIR}/pmd_Mutex.o

####################################BatteryObserver############################################

${BINDIR}/pmd_BatteryObserver_ut.bin: DEFINES+=-DUNITTEST 
${BINDIR}/pmd_BatteryObserver_ut.bin: ${OBJDIR}/pmd_BatteryObserver_ut.o 
${BINDIR}/pmd_BatteryObserver_ut.bin: ${OBJDIR}/pmd_BatteryObserver.o 
${BINDIR}/pmd_BatteryObserver_ut.bin: ${OBJDIR}/pmd_DeepSleepInterface.o 
${BINDIR}/pmd_BatteryObserver_ut.bin: ${OBJDIR}/pmd_TemperatureSensor.o

####################################TemperatureSensor############################################

${BINDIR}/pmd_TemperatureSensor_ut.bin: DEFINES+=-DUNITTEST
${BINDIR}/pmd_TemperatureSensor_ut.bin: ${OBJDIR}/pmd_TemperatureSensor.o
${BINDIR}/pmd_TemperatureSensor_ut.bin: ${OBJDIR}/pmd_TemperatureSensor_NTC.o
${BINDIR}/pmd_TemperatureSensor_ut.bin: ${OBJDIR}/pmd_TemperatureSensor_Internal.o
${BINDIR}/pmd_TemperatureSensor_ut.bin: ${OBJDIR}/pmd_TemperatureSensor_ut.o

####################################PIDController############################################

${BINDIR}/pmd_PIDController_ut.bin: DEFINES+=-DUNITTEST
${BINDIR}/pmd_PIDController_ut.bin: ${OBJDIR}/pmd_PIDController.o
${BINDIR}/pmd_PIDController_ut.bin: ${OBJDIR}/pmd_PIDController_ut.o

################################################################################

test: clean-all ${BINDIR} ${OBJDIR} test_binarys
	@echo "Generate coverage report. See ${COVERAGEDIR}/index.html"
	@${LCOV} --directory ${OBJDIR}/ --base-directory ${OBJDIR}/ --gcov-tool ${GCOV} --capture -o ${OBJDIR}/cov.info
	@${GENHTML} ${OBJDIR}/cov.info -o ${COVERAGEDIR}

TESTS=${BINDIR}/pmd_DebugInterface_ut.bin
TESTS+=${BINDIR}/pmd_BatteryObserver_ut.bin
TESTS+=${BINDIR}/pmd_TemperatureSensor_ut.bin	
TESTS+=${BINDIR}/pmd_PIDController_ut.bin

test_binarys: ${TESTS}  
	@echo "-------------------------------------------------------------"
	@echo "-------------------------------------------------------------"
	@$(foreach test,$^,./$(test);)	
	@echo "-------------------------------------------------------------"
	@echo "-------------------------------------------------------------"	
