#!/bin/bash

protected_branch='master'  
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]  
then  
    read -p "You're about to push master, is that what you intended? Type 'I KNOW WHAT I DO!' : " -n 17 -r < /dev/tty
    echo
    if echo $REPLY | grep -E 'I KNOW WHAT I DO!' > /dev/null
    then
        exit 0 # push will execute
    fi
    exit 1 # push will not execute
else  
    exit 0 # push will execute
fi  
