IPATH+=${ROOT}/sources
IPATH+=${ROOT}/sources/app
IPATH+=${ROOT}/sources/os
IPATH+=${ROOT}/sources/dev
IPATH+=${ROOT}/sources/interface
IPATH+=${ROOT}/sources/utility
IPATH+=${ROOT}/sources/hal_stm32f10x
IPATH+=${RTOS_SOURCE_DIR}/include
IPATH+=${RTOS_SOURCE_DIR}
IPATH+=${RTOS_SOURCE_DIR}/portable/GCC/ARM_CM3
IPATH+=${ROOT}/libraries/STM32F10x_StdPeriph_Driver/inc
IPATH+=${ROOT}/libraries/CMSIS/Include
IPATH+=${ROOT}/libraries/CMSIS/Device/ST/STM32F10x
IPATH+=${ROOT}/libraries
IPATH+=${PRJ_PATH}/config

IPATH+=${ROOT}/libraries/SystemView_Src_V240a/SEGGER
IPATH+=${ROOT}/libraries/SystemView_Src_V240a/OS
IPATH+=${ROOT}/libraries/SystemView_Src_V240a/Config

VPATH+=${ROOT}/sources
VPATH+=${ROOT}/sources/dev
VPATH+=${ROOT}/sources/os
VPATH+=${ROOT}/sources/app
VPATH+=${ROOT}/sources/interface
VPATH+=${ROOT}/sources/utility
VPATH+=${ROOT}/sources/hal_stm32f10x

####################################binasci############################################

${BINDIR}/binascii_ut.bin: DEFINES+=-DDEBUG
${BINDIR}/binascii_ut.bin: DEFINES+=-DUNITTEST
${BINDIR}/binascii_ut.bin: ${OBJDIR}/binascii_ut.o

####################################isotp############################################

${BINDIR}/IsoTp_ut.bin: DEFINES+=-DDEBUG
${BINDIR}/IsoTp_ut.bin: DEFINES+=-DUNITTEST
${BINDIR}/IsoTp_ut.bin: ${OBJDIR}/IsoTp_ut.o
${BINDIR}/IsoTp_ut.bin: ${OBJDIR}/IsoTp.o


################################################################################

test: clean-all ${BINDIR} ${OBJDIR} test_binarys
	#@echo "Generate coverage report. See ${COVERAGEDIR}/index.html"
	#-@${LCOV} --directory ${OBJDIR}/ --base-directory ${OBJDIR}/ --gcov-tool ${GCOV} --capture -o ${OBJDIR}/cov.info
	#-@${GENHTML} ${OBJDIR}/cov.info -o ${COVERAGEDIR}

TESTS=${BINDIR}/binascii_ut.bin
TESTS+=${BINDIR}/IsoTp_ut.bin


test_binarys: ${TESTS}  
	@echo "-------------------------------------------------------------"
	@echo "-------------------------------------------------------------"
	@$(foreach test,$^,./$(test);)	
	@echo "-------------------------------------------------------------"
	@echo "-------------------------------------------------------------"	
