IPATH+=${ROOT}/sources
IPATH+=${ROOT}/sources/config
IPATH+=${ROOT}/sources/app
IPATH+=${ROOT}/sources/os
IPATH+=${ROOT}/sources/dev
IPATH+=${ROOT}/sources/interface
IPATH+=${ROOT}/sources/utility
IPATH+=${ROOT}/sources/hal_stm32f4xx
IPATH+=${RTOS_SOURCE_DIR}/include
IPATH+=${RTOS_SOURCE_DIR}/portable/GCC/ARM_CM4F
IPATH+=${ROOT}/libraries/STM32F4xx_StdPeriph_Driver/inc
IPATH+=${ROOT}/libraries/CMSIS/Include
IPATH+=${ROOT}/libraries/CMSIS/Device/ST/STM32F4xx/Include
IPATH+=${ROOT}/libraries
IPATH+=${PRJ_PATH}/config

IPATH+=${ROOT}/libraries/SystemView_Src_V240a/SEGGER
IPATH+=${ROOT}/libraries/SystemView_Src_V240a/OS
IPATH+=${ROOT}/libraries/SystemView_Src_V240a/Config

VPATH+=${ROOT}/sources
VPATH+=${ROOT}/sources/dev
VPATH+=${ROOT}/sources/os
VPATH+=${ROOT}/sources/app
VPATH+=${ROOT}/sources/interface
VPATH+=${ROOT}/sources/hal_stm32f4xx

####################################DebugInterface############################################

${BINDIR}/DebugInterface_ut.bin: DEFINES+=-DDEBUG
${BINDIR}/DebugInterface_ut.bin: DEFINES+=-DUNITTEST
${BINDIR}/DebugInterface_ut.bin: ${OBJDIR}/DebugInterface_ut.o 
${BINDIR}/DebugInterface_ut.bin: ${OBJDIR}/DebugInterface.o
${BINDIR}/DebugInterface_ut.bin: ${OBJDIR}/Mutex.o

####################################PIDController############################################

${BINDIR}/PIDController_ut.bin: DEFINES+=-DUNITTEST
${BINDIR}/PIDController_ut.bin: ${OBJDIR}/PIDController.o
${BINDIR}/PIDController_ut.bin: ${OBJDIR}/PIDController_ut.o

##################################### OsTestMockup ###########################################

${BINDIR}/OsTestMockup_ut.bin: DEFINES +=-DUNITTEST
${BINDIR}/OsTestMockup_ut.bin:  DEFINES +=-pthread
${BINDIR}/OsTestMockup_ut.bin: ${OBJDIR}/OsTestMockup_ut.o
${BINDIR}/OsTestMockup_ut.bin: ${OBJDIR}/MutexTestMockup.o
${BINDIR}/OsTestMockup_ut.bin: ${OBJDIR}/SemaphoreTestMockup.o
${BINDIR}/OsTestMockup_ut.bin: ${OBJDIR}/TaskTestMockup.o
${BINDIR}/OsTestMockup_ut.bin: ${OBJDIR}/TaskInterruptableTestMockup.o

################################################################################

test: clean-all ${BINDIR} ${OBJDIR} test_binarys
	@echo "Generate coverage report. See ${COVERAGEDIR}/index.html"
	-@${LCOV} --directory ${OBJDIR}/ --base-directory ${OBJDIR}/ --gcov-tool ${GCOV} --capture -o ${OBJDIR}/cov.info
	-@${GENHTML} ${OBJDIR}/cov.info -o ${COVERAGEDIR}

TESTS=${BINDIR}/DebugInterface_ut.bin
TESTS+=${BINDIR}/PIDController_ut.bin
TESTS+=${BINDIR}/OsTestMockup_ut.bin

test_binarys: ${TESTS}  
	@echo "-------------------------------------------------------------"
	@echo "-------------------------------------------------------------"
	@$(foreach test,$^,./$(test);)	
	@echo "-------------------------------------------------------------"
	@echo "-------------------------------------------------------------"	
